= Текст выступления
:toc:

== Слайд 3
Бизнес регулярно сталкивается с задачами, которые можно эффективно решить с помощью алгоритмов машинного обучения:

* Классификация спам/не спам
* Распознавание образов на видео
* Обнаружение и фильтрация недопустимого или даже запрещённого контента
* и пр

(показать вторую часть слайда)

Практика при этом показывает, что такие задачи похожи или имеют типовое решение.

== Слайд 4
Решение при этом сводится к двум вещам:

. Решение задачи машинного обучения:
    * Постановка задачи
    * Сбор и разметка данных
    * Выбор архитектуры
    * Обучение и валидация
. Публикация модели и данных
    * В виде Google Colab ноутбука
    ** В России никогда не было возможности получить премиум-доступ
    * В виде своей странички:
    ** Приходится администрировать свой сервер
    ** Приходится писать код
    ** Платить за хостинг

== Слайд 6
В Одноклассниках с этими задачами также сталкиваются,
и уже наработали некоторые элементы типовых решений:

* Краудсорсинговое приложение для разметки данных
  (люди за небольшую плату выполняют простые несистемные задания)
* Неструктурированный набор предобученных моделей для разных типов задач
* Сервис для публикации моделей вида «загрузить данные -- получить ответ модели»
* Инфраструктура хранения и обработки данных

Имеет смысл собрать все эти элементы в один сервис.

== Слайд 7
Существующие аналоги:

. https://www.kaggle.com/
    * Изучение машинного обучения
    * Написание своих и изучения чужих прогнозных моделей
    * Проведение контестов
    * Форум
. https://www.drivendata.org/
    * Формирование проблемы
    * Проведение соревнований
    * Интеграция лучшей модели в процесс организации
. https://www.topcoder.com/
    * Исследование данных и анализ
    * Постановка проблемы на основе данных
    * Применение алгоритмов к данным
. https://boosters.pro/ (краудсорсинг)
    * Помощь с развитием Data Science процессов
    * Постановка проблемы и предоставление решения для бизнес задач
    * Проведение контестов
    * Форум
. https://unearthed.solutions/ (краудсорсинг)
    * Формирование проблемы
    * Платформа для проведения контестов
    * Интеграция лучшей модели в процесс организации
. https://www.crowdai.com/ (краудсорсинг)
    * Объединение данных в единую библиотеку
    * Обработка и анализ данных
    * Обучение и масштабирование моделей
    * Интеграция модели в процесс организации
. https://www.datafountain.cn/
    * Платформа для соревнований
    * Форум
    * Открытое хранение данных для различных областей
    * Интеграция лучшей модели в процесс организаций

== Слайд 9
Цель работы -- разработать платформу, которая объединит наработки Одноклассников в один сервис.

Задачи:

. Разработать архитектуру платформы
. Разработать фронтэнд веб-сайта
. Разработать бэкэнд
. Разработать клиент для инфраструктуры Одноклассников

Я занимаюсь непосредственно инфраструктурой (задача 4),
также мне нужно принимать во внимание архитектуру платформы.

== Слайд 10
Архитектура платформы состоит из:

* Фронэнда
* Бэкэнда
* Клиента для инфраструктуры

Общение между ними происходит по сети.

Бэкэнд и клиент инфраструктуры имеют свои собственные базы данных.
Они могут быть физически расположены на одной машине,
но их таблицы не пересекаются.

== Слайд 12
Инфраструктура включает в себя:

* Взаимодействие с Airflow API
* Конечный автомат состояний одной модели
* Взаимодействие с Cassandra

Я занимаюсь взаимодействием с Airflow API
и конечным автоматом,
Илькин -- взаимодействием с БД.

== Слайд 13
Чем обусловлен выбор технологий?

Airflow и Cassandra уже развёрнуты у Одноклассников.

В качестве основы сервиса используются Java и Spring Boot,
чтобы ОК могли поддерживать сервис после завершения НИР.

== Слайд 14
На слайде вы можете видеть схему
разработанного конечного автомата одного процесса.

Сервис периодически опрашивает Airflow
о состоянии процессов,
обновляет запись в БД и пытается перевести
процесс из одного состояния в другое в соответствии
с конечным автоматом.

== Слайд 16
Итак, я перечислил задачи и планы.
Что же из этого успели реализовать?

Почти все взаимодействия с Airflow.

== Слайд 17
Конечный автомат реализован частично.

== Слайд 18
В планах остался экспорт метрик моделей.

Также в ходе разработки стало понятно,
что сильно помогут автоматизированные тесты системы.
Сервис состоит почти целиком из сетевых
взаимодействий с изменяемыми состояниями,
поэтому как реализовать тесты ещё предстоит придумать.

== Слайд 19
Какие возникли блокеры:

* Долгое получение доступов.
  В результате доступы к рабочему окружению появились уже к началу сессии.
* Взаимодействие с базой данных.
  Упёрлись в скорость взаимодействия людей.
  Пока в качестве заглушки сервис читает статическое состояние из БД
  и использует его.
